### ISSUE TITLE
Most model cells don't have an info file

### ISSUE THREAD

**Issue by saschuta** [relacs/rlx2nix#1]
Many of the P-units dat files are gziped. Cells of the model population with this problem:
['2012-06-27-ah-invivo-1',
 '2012-06-27-an-invivo-1',
 '2012-07-03-ak-invivo-1',
 '2012-07-12-ag-invivo-1',
 '2012-07-12-ap-invivo-1',
 '2012-12-13-af-invivo-1',
 '2012-12-13-ag-invivo-1',
 '2012-12-13-ah-invivo-1',
 '2012-12-13-an-invivo-1',
 '2012-12-13-ao-invivo-1',
 '2012-12-20-aa-invivo-1',
 '2012-12-20-ab-invivo-1',
 '2012-12-20-ac-invivo-1',
 '2012-12-20-ad-invivo-1',
 '2012-12-20-ae-invivo-1',
 '2012-12-21-ai-invivo-1',
 '2012-12-21-ak-invivo-1',
 '2012-12-21-am-invivo-1',
 '2012-12-21-an-invivo-1',
 '2013-01-08-aa-invivo-1',
 '2014-06-06-ac-invivo-1',
 '2014-12-03-ai-invivo-1',
 '2014-12-11-aa-invivo-1',
 '2014-12-11-ad-invivo-1',
 '2015-01-20-ae-invivo-1',
 '2015-01-20-af-invivo-1']

**Comment by jgrewe** [comment]
I think we resolved this issue, right? Closing it
